"""empty message

Revision ID: 7ba83d22eece
Revises: eb718335cea1
Create Date: 2026-02-08 18:58:24.373900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba83d22eece'
down_revision = 'eb718335cea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('weekdays', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('skip_next', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('snooze_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('travel_pause_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_schedule', schema=None) as batch_op:
        batch_op.drop_column('travel_pause_until')
        batch_op.drop_column('snooze_until')
        batch_op.drop_column('skip_next')
        batch_op.drop_column('delivery_time')
        batch_op.drop_column('weekdays')
        batch_op.drop_column('frequency_type')

    # ### end Alembic commands ###
