"""Added is_paused field to ReadingSchedule

Revision ID: eb718335cea1
Revises: 
Create Date: 2025-03-08 07:58:58.944392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb718335cea1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paused', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_schedule', schema=None) as batch_op:
        batch_op.drop_column('is_paused')

    # ### end Alembic commands ###
